name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]    # ← adapte si ta branche est différente
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check deployment token
        run: |
          if [ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
            echo "❌ Missing AZURE_STATIC_WEB_APPS_API_TOKEN secret"
            exit 1
          fi
          echo "✅ Deployment token present"

      - name: Deploy Static Web App (no build)
  uses: Azure/static-web-apps-deploy@v1
  with:
    repo_token: ${{ secrets.GITHUB_TOKEN }}
    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    action: upload
    app_location: /           # ← mets ici ton sous-dossier si tes fichiers ne sont pas à la racine
    api_location: ""
    output_location: /        # ← identique à app_location
    skip_app_build: true      # ← désactive Oryx/npm build
    is_static_export: true

