name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]   # ← adapte si ta branche est autre
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Static Web App (no build)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: /          # ← mets le SOUS-DOSSIER si ton site n’est pas à la racine
          api_location: ""         # ← vide = pas d’API/Functions
          output_location: /       # ← identique à app_location
          skip_app_build: true     # ← désactive Oryx/npm build
          is_static_export: true
