name: Azure Static Web Apps CI/CD (calm-grass-039d60d03)

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # (facultatif mais utile en cas d'erreur)
      - name: Debug repository tree
        run: |
          echo "PWD=$(pwd)"
          ls -la

      - name: Upload static site to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # 🔐 DOIT correspondre au secret contenant le Deployment token
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_GRASS_039D60D03 }}

          # 🚀 Déploiement d'un site statique déjà prêt (pas de build)
          action: upload
          app_location: "/"     
          output_location: ""    # pas de répertoire de build
          api_location: ""       # pas d'API
          skip_app_build: true   # évite Oryx
          skip_api_build: true
          production_branch: main
          deployment_environment: production

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: close




